<?php

declare(strict_types=1);

/*
 * This file is part of forecast.it.fill project.
 * (c) Patrick Jaja <patrickjajaa@gmail.com>
 * This source file is subject to the MIT license that is bundled
 * with this source code in the file LICENSE.
 */

namespace ForecastAutomation\ProjektronClient\Business;

class PayloadDTO {
    private $data;

    public function __construct() {
        $this->data = [
            'daytimerecording,__componentTitleComposed' => 'true',
            'daytimerecording,formsubmitted' => 'true',
            'daytimerecording,Data_FirstOnPage' => 'daytimerecording',
            'daytimerecording,dialog_group_visible_options' => 'true',
            'daytimerecording,Settings,SettingsDefinitions,DisplayOptions,boardColumnContent0,boardColumnContent0_editortype' => 'TokenInput',
            'daytimerecording,Settings,SettingsDefinitions,DisplayOptions,boardColumnContent0,boardColumnContent0_availableTokens' => '{"availableTokens":[{"key":"daytimerecordingAttendance","label":"Anwesenheiten"},{"key":"daytimerecordingAllBookingsOfTheDay","label":"Buchungen des Tages"},{"key":"singleeffort","label":"Einzelbuchen"}]}',
            'daytimerecording,Settings,SettingsDefinitions,DisplayOptions,boardColumnContent0,boardColumnContent0' => '{"JMultiString":[{"name":"Einzelbuchen","relatedOid":"singleeffort_JTemp","token_id":"singleeffort_JTemp","key":"singleeffort"},{"name":"Buchungen des Tages","relatedOid":"daytimerecordingAllBookingsOfTheDay_JTemp","token_id":"daytimerecordingAllBookingsOfTheDay_JTemp","key":"daytimerecordingAllBookingsOfTheDay"}]}',
            'daytimerecording,Settings,SettingsDefinitions,DisplayOptions,boardColumnContent0,boardColumnContent0_search' => '',
            'daytimerecording,settings_dialog_opened' => 'false',
            'daytimerecording,filters_has_unapplied_changes' => 'false',
            'daytimerecording,Selections,effortRecordingDate,year' => '',
            'daytimerecording,Selections,effortRecordingDate,month' => '',
            'daytimerecording,Selections,effortRecordingDate,day' => '',
            'daytimerecording,Selections,effortRecordingDate,__calendar_state' => 'D20240812', // hier day
            'daytimerecording,Selections,effortRecordingDate,__calendarattribute' => 'effortRecordingDate',
            'daytimerecording,Data_FirstOnPage' => 'daytimerecording',
            'daytimerecording,Content,singleeffort,TaskSelector,fixedtask,Data_CustomTitle' => 'Einzelbuchen',
            'daytimerecording,Content,singleeffort,TaskSelector,fixedtask,Data_FirstOnPage' => 'daytimerecording',
            'daytimerecording,Content,singleeffort,TaskSelector,fixedtask,Data_FirstOnPage' => 'daytimerecording',
            'daytimerecording,Content,singleeffort,TaskSelector,fixedtask,task,task' => '1701894153411_JTask', // task
            'daytimerecording,Content,singleeffort,TaskSelector,fixedtask,task,task_entityname' => 'Agile Events (non-billable)', // wahrscheinlich egal
            'daytimerecording,Content,singleeffort,TaskSelector,fixedtask,selectedTaskSummary,selectedTaskSummaryWithInterval,Data_FirstOnPage' => 'daytimerecording',
            'daytimerecording,Content,singleeffort,TaskSelector,fixedtask,selectedTaskSummary,selectedTaskSummaryWithInterval,Data_FirstOnPage' => 'daytimerecording',
            'daytimerecording,Content,singleeffort,TaskSelector,fixedtask,selectedTaskSummary,selectedTaskSummaryWithInterval,Data_SuppressLastHorizontalLine' => 'true',
            'daytimerecording,Content,singleeffort,TaskSelector,fixedtask,oid' => '1725574358961_JEffort',
            'daytimerecording,Content,singleeffort,TaskSelector,fixedtask,Data_SuppressLastHorizontalLine' => 'true',
            'daytimerecording,Content,singleeffort,TaskSelector,fixedtask,edit_form_data_submitted' => 'true',
            'daytimerecording,Content,singleeffort,EffortEditor,effort1,Data_FirstOnPage' => 'daytimerecording',
            'daytimerecording,Content,singleeffort,EffortEditor,effort1,Data_FirstOnPage' => 'daytimerecording',
            'daytimerecording,Content,singleeffort,EffortEditor,effort1,effortStart,effortStart_hour' => '',
            'daytimerecording,Content,singleeffort,EffortEditor,effort1,effortStart,effortStart_minute' => '',
            'daytimerecording,Content,singleeffort,EffortEditor,effort1,effortEnd,effortEnd_hour' => '',
            'daytimerecording,Content,singleeffort,EffortEditor,effort1,effortEnd,effortEnd_minute' => '',
            'daytimerecording,Content,singleeffort,EffortEditor,effort1,effortExpense,effortExpense_hour' => '0', // hour
            'daytimerecording,Content,singleeffort,EffortEditor,effort1,effortExpense,effortExpense_minute' => '01', // hour
            'daytimerecording,Content,singleeffort,EffortEditor,effort1,effortChargeability,effortChargeability' => 'effortIsChargable_true+effortIsShown_true',
            'daytimerecording,Content,singleeffort,EffortEditor,effort1,effortActivity,effortActivity' => 'anrechenbar',
            'daytimerecording,Content,singleeffort,EffortEditor,effort1,effortActivity,effortActivity_widgetType' => 'option',
            'daytimerecording,Content,singleeffort,EffortEditor,effort1,effortWorkingTimeType,effortWorkingTimeType' => 'Standard',
            'daytimerecording,Content,singleeffort,EffortEditor,effort1,description,description' => 'curl test automated',
            'daytimerecording,Content,singleeffort,EffortEditor,effort1,indicatorSumForecastExpense,indicatorSumForecastExpense_edited' => 'true',
            'daytimerecording,Content,singleeffort,EffortEditor,effort1,forecastEstimationComment,forecastEstimationComment' => '',
            'daytimerecording,Content,singleeffort,EffortEditor,effort1,oid' => '1725574358961_JEffort', // task
            'daytimerecording,Content,singleeffort,EffortEditor,effort1,Data_SuppressLastHorizontalLine' => 'false',
            'daytimerecording,Content,singleeffort,EffortEditor,effort1,edit_form_data_submitted' => 'true',
            'daytimerecording,Content,singleeffort,recordType' => 'neweffort',
            'daytimerecording,Content,singleeffort,recordOid' => '',
            'daytimerecording,Content,singleeffort,recordDate' => '1726092000000', // day
            'daytimerecording,Content,singleeffort,Data_SuppressLastHorizontalLine' => 'true',
            'daytimerecording,Content,daytimerecordingAllBookingsOfTheDay,Data_CustomTitle' => 'Buchungen des Tages',
            'daytimerecording,Content,daytimerecordingAllBookingsOfTheDay,Data_FirstOnPage' => 'daytimerecording',
            'daytimerecording,Content,daytimerecordingAllBookingsOfTheDay,dialog_group_visible_filters' => 'true',
            'daytimerecording,Content,daytimerecordingAllBookingsOfTheDay,Settings,SettingsDefinitions,filterpermanency_effortTargetOid.name' => 'true',
            'daytimerecording,Content,daytimerecordingAllBookingsOfTheDay,filtervisibility_effortTargetOid.name' => 'false',
            'daytimerecording,Content,daytimerecordingAllBookingsOfTheDay,Settings,SettingsDefinitions,filteroperator_effortTargetOid.name' => 'like',
            'daytimerecording,Content,daytimerecordingAllBookingsOfTheDay,Settings,SettingsDefinitions,FilterTerms,effortTargetOid.name,effortTargetOid.name' => '',
            'daytimerecording,Content,daytimerecordingAllBookingsOfTheDay,dialog_group_visible_options' => 'true',
            'daytimerecording,Content,daytimerecordingAllBookingsOfTheDay,Settings,SettingsDefinitions,DisplayOptions,showCorrectionBooking,!showCorrectionBooking' => 'true',
            'daytimerecording,Content,daytimerecordingAllBookingsOfTheDay,Settings,SettingsDefinitions,DisplayOptions,durationPattern,durationPattern' => 'defaultDurationPattern',
            'daytimerecording,Content,daytimerecordingAllBookingsOfTheDay,Settings,SettingsDefinitions,DisplayOptions,doNotMarkZeroValues,!doNotMarkZeroValues' => 'true',
            'daytimerecording,Content,daytimerecordingAllBookingsOfTheDay,Settings,SettingsDefinitions,DisplayOptions,doNotMarkZeroValues,doNotMarkZeroValues' => 'true',
            'daytimerecording,Content,daytimerecordingAllBookingsOfTheDay,dialog_group_visible_columns' => 'false',
            'daytimerecording,Content,daytimerecordingAllBookingsOfTheDay,!columntoggle_effortTargetOidParentPath' => 'true',
            'daytimerecording,Content,daytimerecordingAllBookingsOfTheDay,!columntoggle_effortTargetOid' => 'true',
            'daytimerecording,Content,daytimerecordingAllBookingsOfTheDay,Settings,SettingsDefinitions,columntoggle_effortTargetOid' => 'true',
            'daytimerecording,Content,daytimerecordingAllBookingsOfTheDay,!columntoggle_effortTargetOid.grandParentOid' => 'true',
            'daytimerecording,Content,daytimerecordingAllBookingsOfTheDay,Settings,SettingsDefinitions,columntoggle_effortTargetOid.grandParentOid' => 'true',
            'daytimerecording,Content,daytimerecordingAllBookingsOfTheDay,!columntoggle_effortTargetOid.parentOid' => 'true',
            'daytimerecording,Content,daytimerecordingAllBookingsOfTheDay,!columntoggle_effortAnnotationOid' => 'true',
            'daytimerecording,Content,daytimerecordingAllBookingsOfTheDay,Settings,SettingsDefinitions,columntoggle_effortAnnotationOid' => 'true',
            'daytimerecording,Content,daytimerecordingAllBookingsOfTheDay,!columntoggle_effortEventRefOid' => 'true',
            'daytimerecording,Content,daytimerecordingAllBookingsOfTheDay,!columntoggle_effortWorkflowOid' => 'true',
            'daytimerecording,Content,daytimerecordingAllBookingsOfTheDay,!columntoggle_effortTargetUserOid' => 'true',
            'daytimerecording,Content,daytimerecordingAllBookingsOfTheDay,!columntoggle_effortStart' => 'true',
            'daytimerecording,Content,daytimerecordingAllBookingsOfTheDay,Settings,SettingsDefinitions,columntoggle_effortStart' => 'true',
            'daytimerecording,Content,daytimerecordingAllBookingsOfTheDay,!columntoggle_effortEnd' => 'true',
            'daytimerecording,Content,daytimerecordingAllBookingsOfTheDay,Settings,SettingsDefinitions,columntoggle_effortEnd' => 'true',
            'daytimerecording,Content,daytimerecordingAllBookingsOfTheDay,!columntoggle_description' => 'true',
            'daytimerecording,Content,daytimerecordingAllBookingsOfTheDay,Settings,SettingsDefinitions,columntoggle_description' => 'true',
            'daytimerecording,Content,daytimerecordingAllBookingsOfTheDay,!columntoggle_dateProgressIndicator' => 'true',
            'daytimerecording,Content,daytimerecordingAllBookingsOfTheDay,!columntoggle_effortProgressIndicator' => 'true',
            'daytimerecording,Content,daytimerecordingAllBookingsOfTheDay,!columntoggle_referenceState' => 'true',
            'daytimerecording,Content,daytimerecordingAllBookingsOfTheDay,!columntoggle_effortRefInfo' => 'true',
            'daytimerecording,Content,daytimerecordingAllBookingsOfTheDay,!columntoggle_effortChargeability' => 'true',
            'daytimerecording,Content,daytimerecordingAllBookingsOfTheDay,!columntoggle_effortActivity' => 'true',
            'daytimerecording,Content,daytimerecordingAllBookingsOfTheDay,!columntoggle_effortWorkingTimeType' => 'true',
            'daytimerecording,Content,daytimerecordingAllBookingsOfTheDay,!columntoggle_effortUserGroupReference2' => 'true',
            'daytimerecording,Content,daytimerecordingAllBookingsOfTheDay,!columntoggle_closeReferenceState' => 'true',
            'daytimerecording,Content,daytimerecordingAllBookingsOfTheDay,Settings,SettingsDefinitions,columntoggle_closeReferenceState' => 'true',
            'daytimerecording,Content,daytimerecordingAllBookingsOfTheDay,!columntoggle_effortTargetOid.startDate' => 'true',
            'daytimerecording,Content,daytimerecordingAllBookingsOfTheDay,!columntoggle_effortTargetOid.endDate' => 'true',
            'daytimerecording,Content,daytimerecordingAllBookingsOfTheDay,!columntoggle_timerecordingTotalValues' => 'true',
            'daytimerecording,Content,daytimerecordingAllBookingsOfTheDay,Settings,SettingsDefinitions,columntoggle_timerecordingTotalValues' => 'true',
            'daytimerecording,Content,daytimerecordingAllBookingsOfTheDay,!columntoggle_timerecordingTotalValues:indicatorSumDedicatedExpense' => 'true',
            'daytimerecording,Content,daytimerecordingAllBookingsOfTheDay,Settings,SettingsDefinitions,columntoggle_timerecordingTotalValues:indicatorSumDedicatedExpense' => 'true',
            'daytimerecording,Content,daytimerecordingAllBookingsOfTheDay,!columntoggle_timerecordingTotalValues:indicatorSumRealExpense' => 'true',
            'daytimerecording,Content,daytimerecordingAllBookingsOfTheDay,Settings,SettingsDefinitions,columntoggle_timerecordingTotalValues:indicatorSumRealExpense' => 'true',
            'daytimerecording,Content,daytimerecordingAllBookingsOfTheDay,!columntoggle_timerecordingTotalValues:indicatorSumForecastExpense' => 'true',
            'daytimerecording,Content,daytimerecordingAllBookingsOfTheDay,!columntoggle_timerecordingTotalValues:forecastEstimationComment' => 'true',
            'daytimerecording,Content,daytimerecordingAllBookingsOfTheDay,!columntoggle_timerecordingCurrentIntervalValues' => 'true',
            'daytimerecording,Content,daytimerecordingAllBookingsOfTheDay,!columntoggle_timerecordingCurrentIntervalValues:currentInterval.indicatorSumDedicatedExpense' => 'true',
            'daytimerecording,Content,daytimerecordingAllBookingsOfTheDay,Settings,SettingsDefinitions,columntoggle_timerecordingCurrentIntervalValues:currentInterval.indicatorSumDedicatedExpense' => 'true',
            'daytimerecording,Content,daytimerecordingAllBookingsOfTheDay,!columntoggle_timerecordingCurrentIntervalValues:currentInterval.indicatorSumRealExpense' => 'true',
            'daytimerecording,Content,daytimerecordingAllBookingsOfTheDay,Settings,SettingsDefinitions,columntoggle_timerecordingCurrentIntervalValues:currentInterval.indicatorSumRealExpense' => 'true',
            'daytimerecording,Content,daytimerecordingAllBookingsOfTheDay,!columntoggle_timerecordingCurrentIntervalValues:currentInterval.indicatorSumForecastExpense' => 'true',
            'daytimerecording,Content,daytimerecordingAllBookingsOfTheDay,!columntoggle_createBookings' => 'true',
            'daytimerecording,Content,daytimerecordingAllBookingsOfTheDay,Settings,SettingsDefinitions,columntoggle_createBookings' => 'true',
            'daytimerecording,Content,daytimerecordingAllBookingsOfTheDay,!columntoggle_createBookings:[createEffort]' => 'true',
            'daytimerecording,Content,daytimerecordingAllBookingsOfTheDay,!columntoggle_createBookings:[linkToListEffortRecording]' => 'true',
            'daytimerecording,Content,daytimerecordingAllBookingsOfTheDay,dialog_group_visible_sorting' => 'false',
            'daytimerecording,Content,daytimerecordingAllBookingsOfTheDay,Settings,SettingsDefinitions,sort_criteria0' => 'effortStart#DESC',
            'daytimerecording,Content,daytimerecordingAllBookingsOfTheDay,Settings,SettingsDefinitions,sort_criteria1' => '*',
            'daytimerecording,Content,daytimerecordingAllBookingsOfTheDay,Settings,SettingsDefinitions,sort_criteria2' => '*',
            'daytimerecording,Content,daytimerecordingAllBookingsOfTheDay,Settings,SettingsDefinitions,sort_criteria3' => '*',
            'daytimerecording,Content,daytimerecordingAllBookingsOfTheDay,settings_dialog_opened' => 'false',
            'daytimerecording,Content,daytimerecordingAllBookingsOfTheDay,filters_has_unapplied_changes' => 'false',
            'daytimerecording,Content,daytimerecordingAllBookingsOfTheDay,Data_FirstOnPage' => 'daytimerecording',
//            'daytimerecording,Content,daytimerecordingAllBookingsOfTheDay,1725573779496_JEffort_helper' => '{"daytimerecording,Content,daytimerecordingAllBookingsOfTheDay,1725573779496_JEffort_subtyp":"Personal","daytimerecording,Content,daytimerecordingAllBookingsOfTheDay,Columns,SELECTION,listeditoid_1725573779496_JEffort.SELECTION.islisteditable":"y","daytimerecording,Content,daytimerecordingAllBookingsOfTheDay,Columns,closeReferenceState,listeditoid_1725573779496_JEffort.closeReferenceState.islisteditable":"y","daytimerecording,Content,daytimerecordingAllBookingsOfTheDay,Columns,effortEnd,listeditoid_1725573779496_JEffort.effortEnd.islisteditable":"y","daytimerecording,Content,daytimerecordingAllBookingsOfTheDay,Columns,description,listeditoid_1725573779496_JEffort.description.islisteditable":"y","daytimerecording,Content,daytimerecordingAllBookingsOfTheDay,1725573779496_JEffort_lastUpdate":1725954145340,"daytimerecording,Content,daytimerecordingAllBookingsOfTheDay,Columns,[plusminus],[plusminus].islisteditable":"y","daytimerecording,Content,daytimerecordingAllBookingsOfTheDay,Columns,effortExpense,listeditoid_1725573779496_JEffort.effortExpense.islisteditable":"y","daytimerecording,Content,daytimerecordingAllBookingsOfTheDay,Columns,[plusminus],duplicateEffortRow,listeditoid_1725573779496_JEffort.duplicateEffortRow.islisteditable":"y","daytimerecording,Content,daytimerecordingAllBookingsOfTheDay,Columns,effortStart,listeditoid_1725573779496_JEffort.effortStart.islisteditable":"y"}', // one entry
//            'daytimerecording,Content,daytimerecordingAllBookingsOfTheDay,Columns,recordOid,listeditoid_1725573779496_JEffort.recordOid' => '1725573779496_JEffort',
//            'daytimerecording,Content,daytimerecordingAllBookingsOfTheDay,Columns,recordType,listeditoid_1725573779496_JEffort.recordType' => 'effort',
//            'daytimerecording,Content,daytimerecordingAllBookingsOfTheDay,Columns,recordDate,listeditoid_1725573779496_JEffort.recordDate' => '10.09.2024',
//            'daytimerecording,Content,daytimerecordingAllBookingsOfTheDay,Columns,recordUserOid,listeditoid_1725573779496_JEffort.recordUserOid' => '1611701511349_JUser',
//            'daytimerecording,Content,daytimerecordingAllBookingsOfTheDay,Columns,effortTargetOid,listeditoid_1725573779496_JEffort.effortTargetOid' => '1684267402625_JTask',
//            'daytimerecording,Content,daytimerecordingAllBookingsOfTheDay,Columns,effortAnnotationOid,listeditoid_1725573779496_JEffort.effortAnnotationOid' => '',
//            'daytimerecording,Content,daytimerecordingAllBookingsOfTheDay,Columns,effortUserGroupReference,listeditoid_1725573779496_JEffort.effortUserGroupReference' => '',
//            'daytimerecording,Content,daytimerecordingAllBookingsOfTheDay,Columns,effortStart,listeditoid_1725573779496_JEffort.effortStart_hour' => '',
//            'daytimerecording,Content,daytimerecordingAllBookingsOfTheDay,Columns,effortStart,listeditoid_1725573779496_JEffort.effortStart_minute' => '',
//            'daytimerecording,Content,daytimerecordingAllBookingsOfTheDay,Columns,effortEnd,listeditoid_1725573779496_JEffort.effortEnd_hour' => '',
//            'daytimerecording,Content,daytimerecordingAllBookingsOfTheDay,Columns,effortEnd,listeditoid_1725573779496_JEffort.effortEnd_minute' => '',
//            'daytimerecording,Content,daytimerecordingAllBookingsOfTheDay,Columns,effortExpense,listeditoid_1725573779496_JEffort.effortExpense_hour' => '1',
//            'daytimerecording,Content,daytimerecordingAllBookingsOfTheDay,Columns,effortExpense,listeditoid_1725573779496_JEffort.effortExpense_minute' => '15',
//            'daytimerecording,Content,daytimerecordingAllBookingsOfTheDay,Columns,description,listeditoid_1725573779496_JEffort.description' => 'test generated',
//            'daytimerecording,Content,daytimerecordingAllBookingsOfTheDay,Columns,[plusminus],listeditoid_1725573779496_JEffort.[plusminus].editable_children' => 'duplicateEffortRow',
//            'daytimerecording,Content,daytimerecordingAllBookingsOfTheDay,Columns,closeReferenceState,!listeditoid_1725573779496_JEffort.closeReferenceState' => 'true',
//            'daytimerecording,Content,daytimerecordingAllBookingsOfTheDay,1725573780102_JEffort_helper' => '{"daytimerecording,Content,daytimerecordingAllBookingsOfTheDay,Columns,effortStart,listeditoid_1725573780102_JEffort.effortStart.islisteditable":"y","daytimerecording,Content,daytimerecordingAllBookingsOfTheDay,1725573780102_JEffort_subtyp":"Personal","daytimerecording,Content,daytimerecordingAllBookingsOfTheDay,1725573780102_JEffort_lastUpdate":1725954220755,"daytimerecording,Content,daytimerecordingAllBookingsOfTheDay,Columns,effortExpense,listeditoid_1725573780102_JEffort.effortExpense.islisteditable":"y","daytimerecording,Content,daytimerecordingAllBookingsOfTheDay,Columns,description,listeditoid_1725573780102_JEffort.description.islisteditable":"y","daytimerecording,Content,daytimerecordingAllBookingsOfTheDay,Columns,[plusminus],[plusminus].islisteditable":"y","daytimerecording,Content,daytimerecordingAllBookingsOfTheDay,Columns,SELECTION,listeditoid_1725573780102_JEffort.SELECTION.islisteditable":"y","daytimerecording,Content,daytimerecordingAllBookingsOfTheDay,Columns,effortEnd,listeditoid_1725573780102_JEffort.effortEnd.islisteditable":"y"}',
//            'daytimerecording,Content,daytimerecordingAllBookingsOfTheDay,Columns,recordOid,listeditoid_1725573780102_JEffort.recordOid' => '1725573897694_JEffort',
//            'daytimerecording,Content,daytimerecordingAllBookingsOfTheDay,Columns,recordType,listeditoid_1725573780102_JEffort.recordType' => 'effort',
//            'daytimerecording,Content,daytimerecordingAllBookingsOfTheDay,Columns,recordDate,listeditoid_1725573780102_JEffort.recordDate' => '10.09.2024',
//            'daytimerecording,Content,daytimerecordingAllBookingsOfTheDay,Columns,recordUserOid,listeditoid_1725573780102_JEffort.recordUserOid' => '1611701511349_JUser',
//            'daytimerecording,Content,daytimerecordingAllBookingsOfTheDay,Columns,effortTargetOid,listeditoid_1725573780102_JEffort.effortTargetOid' => '1701894153411_JTask',
//            'daytimerecording,Content,daytimerecordingAllBookingsOfTheDay,Columns,effortAnnotationOid,listeditoid_1725573780102_JEffort.effortAnnotationOid' => '',
//            'daytimerecording,Content,daytimerecordingAllBookingsOfTheDay,Columns,effortUserGroupReference,listeditoid_1725573780102_JEffort.effortUserGroupReference' => '',
//            'daytimerecording,Content,daytimerecordingAllBookingsOfTheDay,Columns,effortStart,listeditoid_1725573780102_JEffort.effortStart_hour' => '',
//            'daytimerecording,Content,daytimerecordingAllBookingsOfTheDay,Columns,effortStart,listeditoid_1725573780102_JEffort.effortStart_minute' => '',
//            'daytimerecording,Content,daytimerecordingAllBookingsOfTheDay,Columns,effortEnd,listeditoid_1725573780102_JEffort.effortEnd_hour' => '',
//            'daytimerecording,Content,daytimerecordingAllBookingsOfTheDay,Columns,effortEnd,listeditoid_1725573780102_JEffort.effortEnd_minute' => '',
//            'daytimerecording,Content,daytimerecordingAllBookingsOfTheDay,Columns,description,listeditoid_1725573780102_JEffort.description' => 'curl test',
//            'daytimerecording,Content,daytimerecordingAllBookingsOfTheDay,Columns,[plusminus],listeditoid_1725573897694_JEffort.[plusminus].editable_children' => 'duplicateEffortRow',
//            'daytimerecording,Content,daytimerecordingAllBookingsOfTheDay,Columns,closeReferenceState,!listeditoid_1725573897694_JEffort.closeReferenceState' => 'true',
            'daytimerecording,Content,daytimerecordingAllBookingsOfTheDay,ListDisplayLoadTimestamp' => '1726136986425',
            'daytimerecording,Content,daytimerecordingAllBookingsOfTheDay,QueryConditionCode' => '2231967237',
            'daytimerecording,editableComponentNames' => 'daytimerecording,Content,singleeffort daytimerecording,Content,daytimerecordingAllBookingsOfTheDay',

//            'daytimerecording,Content,daytimerecordingAllBookingsOfTheDay,Columns,effortExpense,listeditoid_1725573780102_JEffort.effortExpense_hour' => '0', // one entry
//            'daytimerecording,Content,daytimerecordingAllBookingsOfTheDay,Columns,effortExpense,listeditoid_1725573780102_JEffort.effortExpense_minute' => '15',
//            'daytimerecording,Content,daytimerecordingAllBookingsOfTheDay,ListDisplayLoadTimestamp' => '1725954261884',
//            'daytimerecording,Content,daytimerecordingAllBookingsOfTheDay,QueryConditionCode' => '2205163005',
//            'daytimerecording,editableComponentNames' => 'daytimerecording,Content,singleeffort daytimerecording,Content,daytimerecordingAllBookingsOfTheDay',
            'oid' => '1701894153411_JTask', // task
            'user' => 'Patrick.Schoenfeld@cec.valantic.com',
            'action,MultiComponentDayTimeRecordingAction,daytimerecording' => '0',
            'pagetimestamp' => '1726136986346',
            'transactionId' => '1726136986351-63733922',
            'SingletonComponents,navigator,navigatorName' => 'projects',
            'SingletonComponents,navigator,navigatorMode' => 'tree',
            'SingletonComponents,navigator,settingsName' => 'valantic',
            'SingletonComponents,navigator,settingsType' => 'shared',
            'SingletonComponents,navigator,search' => '',
            'SingletonComponents,navigator,projects,Choices,tree,dialog_group_visible_filters' => 'true',
            'SingletonComponents,navigator,projects,Choices,tree,filtervisibility_FulltextSubfilter' => 'false',
            'SingletonComponents,navigator,projects,Choices,tree,Settings,SettingsDefinitions,filteroperator_FulltextSubfilter' => 'contains_all',
            'SingletonComponents,navigator,projects,Choices,tree,Settings,SettingsDefinitions,FilterTerms,FulltextSubfilter,FulltextSubfilter' => '',
            'SingletonComponents,navigator,projects,Choices,tree,filtervisibility_name' => 'false',
            'SingletonComponents,navigator,projects,Choices,tree,Settings,SettingsDefinitions,filteroperator_name' => 'like',
            'SingletonComponents,navigator,projects,Choices,tree,Settings,SettingsDefinitions,FilterTerms,name,name' => '',
            'SingletonComponents,navigator,projects,Choices,tree,filtervisibility_projectShortname' => 'false',
            'SingletonComponents,navigator,projects,Choices,tree,Settings,SettingsDefinitions,filteroperator_projectShortname' => 'like',
            'SingletonComponents,navigator,projects,Choices,tree,Settings,SettingsDefinitions,FilterTerms,projectShortname,projectShortname' => '',
            'SingletonComponents,navigator,projects,Choices,tree,filtervisibility_typ' => 'false',
            'SingletonComponents,navigator,projects,Choices,tree,Settings,SettingsDefinitions,filteroperator_typ' => '=',
            'SingletonComponents,navigator,projects,Choices,tree,Settings,SettingsDefinitions,FilterTerms,typ,typ' => '*',
            'SingletonComponents,navigator,projects,Choices,tree,filtervisibility_subtyp' => 'false',
            'SingletonComponents,navigator,projects,Choices,tree,Settings,SettingsDefinitions,filteroperator_subtyp' => '=',
            'SingletonComponents,navigator,projects,Choices,tree,Settings,SettingsDefinitions,FilterTerms,subtyp,subtyp' => '*',
            'SingletonComponents,navigator,projects,Choices,tree,Settings,SettingsDefinitions,FilterTerms,subtyp,subtyp_widgetType' => 'option',
            'SingletonComponents,navigator,projects,Choices,tree,filtervisibility_state' => 'false',
            'SingletonComponents,navigator,projects,Choices,tree,Settings,SettingsDefinitions,filteroperator_state' => 'eq_multiple_choice',
            'SingletonComponents,navigator,projects,Choices,tree,Settings,SettingsDefinitions,FilterTerms,state,state_editortype' => 'TokenInput',
            'SingletonComponents,navigator,projects,Choices,tree,Settings,SettingsDefinitions,FilterTerms,state,state_availableTokens' => '{"availableTokens":[{"key":"Planned","label":"Geplant"},{"key":"Offered","label":"Angeboten"},{"key":"Authorised","label":"Beauftragt"},{"key":"Suspended","label":"Unterbrochen"},{"key":"Opened","label":"Offen"},{"key":"Closed","label":"Geschlossen"}]}',
            'SingletonComponents,navigator,projects,Choices,tree,Settings,SettingsDefinitions,FilterTerms,state,state' => '{"JMultiString":[]}',
            'SingletonComponents,navigator,projects,Choices,tree,Settings,SettingsDefinitions,FilterTerms,state,state_search' => '',
            'SingletonComponents,navigator,projects,Choices,tree,filtervisibility_priority' => 'false',
            'SingletonComponents,navigator,projects,Choices,tree,Settings,SettingsDefinitions,filteroperator_priority' => 'eq_multiple_choice',
            'SingletonComponents,navigator,projects,Choices,tree,Settings,SettingsDefinitions,FilterTerms,priority,priority_editortype' => 'TokenInput',
            'SingletonComponents,navigator,projects,Choices,tree,Settings,SettingsDefinitions,FilterTerms,priority,priority_availableTokens' => '{"availableTokens":[{"key":"Prio1","label":"Hoch"},{"key":"Prio3","label":"Niedrig"},{"key":"Prio2","label":"Normal"}]}',
            'SingletonComponents,navigator,projects,Choices,tree,Settings,SettingsDefinitions,FilterTerms,priority,priority' => '{"JMultiString":[]}',
            'SingletonComponents,navigator,projects,Choices,tree,Settings,SettingsDefinitions,FilterTerms,priority,priority_search' => '',
            'SingletonComponents,navigator,projects,Choices,tree,filtervisibility_processModel' => 'false',
            'SingletonComponents,navigator,projects,Choices,tree,Settings,SettingsDefinitions,filteroperator_processModel' => 'eq_multiple_choice',
            'SingletonComponents,navigator,projects,Choices,tree,Settings,SettingsDefinitions,FilterTerms,priority,priority_editortype' => 'TokenInput',
            'SingletonComponents,navigator,projects,Choices,tree,Settings,SettingsDefinitions,FilterTerms,processModel,processModel_availableTokens' => '{"availableTokens":[{"key":"prince2","label":"PRINCE2®"}]}',
            'SingletonComponents,navigator,projects,Choices,tree,Settings,SettingsDefinitions,FilterTerms,processModel,processModel' => '{"JMultiString":[]}',
            'SingletonComponents,navigator,projects,Choices,tree,Settings,SettingsDefinitions,FilterTerms,processModel,processModel_search' => '',
            'SingletonComponents,navigator,projects,Choices,tree,dialog_group_visible_options' => 'true',
            'SingletonComponents,navigator,projects,Choices,tree,Settings,SettingsDefinitions,DisplayOptions,showProjectsMode,showProjectsMode' => 'myReferences',
            'SingletonComponents,navigator,projects,Choices,tree,Settings,SettingsDefinitions,DisplayOptions,showProjectsModeIncludeUserGroups,!showProjectsModeIncludeUserGroups' => 'true',
            'SingletonComponents,navigator,projects,Choices,tree,Settings,SettingsDefinitions,DisplayOptions,showProjectsModeIncludeUserGroups,showProjectsModeIncludeUserGroups' => 'true',
            'SingletonComponents,navigator,projects,Choices,tree,dialog_group_visible_sorting' => 'false',
            'SingletonComponents,navigator,projects,Choices,tree,Settings,SettingsDefinitions,sort_criteria0' => 'oid#ASC',
            'SingletonComponents,navigator,projects,Choices,tree,Settings,SettingsDefinitions,sort_criteria1' => 'siblingIndex#ASC',
            'SingletonComponents,navigator,projects,Choices,tree,Settings,SettingsDefinitions,sort_criteria2' => '*',
            'SingletonComponents,navigator,projects,Choices,tree,settings_dialog_opened' => 'false',
            'SingletonComponents,navigator,projects,Choices,tree,filters_has_unapplied_changes' => 'false',
            'SingletonComponents,navigator,projects,Choices,tree,ListDisplayLoadTimestamp' => '1726136987428',
            'SingletonComponents,navigator,projects,Choices,tree,QueryConditionCode' => '604243187',
            'PageMapSearchAttribute,PageMapSearchAttribute' => '',
            'PageForm,formChangedIndicator' => 'true',
            'BCS.ConfirmDiscardChangesDialog,InitialApplyButtonsOnError' => 'daytimerecording,Apply',
            'PageForm,HighlightedApplyButtonsOnError' => 'daytimerecording,Apply',
            '__setXCoordinate' => '0',
            '__setYCoordinate' => '177',
            'CSRF_Token' => 'B54W-Zkk-aHq9JDFzCIUtOOBjbTYrKmDxRJrh1Ofpck',
            'daytimerecording,Apply' => 'daytimerecording,Apply',
            'submitButtonPressed' => 'daytimerecording,Apply',
        ];
    }

    public function getEncodedData() {
        // URL-encode the data for the POST request
        return http_build_query($this->data);
    }
}
