name: phpstan

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  php-cs-fixer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Install
        run: composer install --ignore-platform-req=ext-amqp

      - name: Run phpstan analyze --configuration phpstan.neon
        run: vendor/bin/phpstan analyze --configuration phpstan.neon

